# Provides automatic merging of pull requests based on specific rules.
#
# See: https://docs.mergify.io/configuration.html

pull_request_rules:
  - name: Automatically merge Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=CheckFormat
      - check-success=RunSpecs
    actions:
      merge:
        method: squash

  - name: When a dependency conflict emerges, ask Dependabot to rebase its update
    conditions:
      - conflict
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      comment:
        message: "@dependabot rebase"
