name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v2.2
        with:
          prettier_options: --write .
