name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v2.2
        with:
          prettier_options: --write .

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - run: npm install

      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: $
