name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v2.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write .        
          
  deploy:  
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: $
